stages:
  - prepare
  - build
  - push

prepare:
  stage: prepare
  script:
    - make stack-deployimage

build:
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AUTHSERVICE_SSH_PRIVKEY")
    - mkdir -p ~/.ssh
    - grep "git.nejla.com" ~/.ssh/known_hosts >/dev/null
      || (echo "$NEJLA_GIT_HOSTKEY" >> ~/.ssh/known_hosts)
  script:
    - make all

push:
  stage: push
  before_script:
    - [[ -n $CI_REGISTRY_NAME ]] || fail "CI_REGISTRY_NAME is undefined"
    - [[ -n $CI_BUILD_TOKEN ]] || fail "CI_BUILD_TOKE is undefined"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE

  script:
    - make push
