stages:
  - prepare
  - build
  - test
  - push

prepare:
  stage: prepare
  script:
    - make stack-deployimage

build:
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AUTHSERVICE_SSH_PRIVKEY")
    - mkdir -p ~/.ssh
    - grep "git.nejla.com" ~/.ssh/known_hosts >/dev/null
      || (echo "$NEJLA_GIT_HOSTKEY" >> ~/.ssh/known_hosts)
  script:
    - make all

test:
  stage: test
  before_script:
    - docker-compose up -d
  script:
    - cd tests && bash ./test dockertest
  after_script:
    - docker-compose down --remove-orphans -v

push:
  stage: push
  before_script:
    - scripts/registry-login

  script:
    - make push
