image: nejla/haskell-build

stages:
  - build
  - test
  - push

variables:
  stack_args: --no-docker

build:
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AUTHSERVICE_SSH_PRIVKEY")
    - mkdir -p ~/.ssh
    - grep "git.nejla.com" ~/.ssh/known_hosts >/dev/null
      || (echo "$NEJLA_GIT_HOSTKEY" >> ~/.ssh/known_hosts)
    - mkdir -p $PWD/.stack-cache
    - '[[ -d $HOME/.stack ]] || ln -s $PWD/.stack-cache $HOME/.stack'
  script:
    - make all
  artifacts:
    paths:
      - backend/dist

test-backend:
  stage: test
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
    DB_HOST: database
  services:
    - name: postgres:10.13
      alias: database
    - name: mailhog/mailhog:latest
      alias: mailhog
  image: registry.nejla.com/nejla-ab/auth-service/baseimage:$CI_COMMIT_SHA
  dependencies:
    - build
  script:
    - for t in backend/dist/tests/*; do echo "Runing $t"; $t; done

push:
  stage: push
  before_script:
    - scripts/registry-login

  script:
    - make push

cache:
  paths:
    - '.stack-cache'
    - 'service/.stack-work'
  key: "auth-service"
