resolver: lts-16.24

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: a5fbeb7f3aa4de723dc7cd5f2482178f1dba992c
  - '../auth-service-core'
  - git: git@git.nejla.com:nejla-ab/signed-auth.git
    commit: 094579cbf2b6017d2f4b601c2ec871958407d401
  - base64-bytestring-1.2.0.1

docker:
  enable: false
  image: nejla/haskell-build

allow-newer: true

nix:
  # shell-file: stack.nix
  packages:
    - zlib
    - postgresql
