##############################################
# NB: Changes to this file shold be reflected
# in stack.dockerhub.yaml !
##############################################

resolver: lts-18.12

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 3cbc5d0db2e8c18838159b92d7bb9b39f551e226
  - '../auth-service-core'
  - base64-bytestring-1.2.0.1
  - git: https://github.com/Philonous/wai-saml2.git
    commit: c8a321798d9e4d08452d415b9f37de89d1ac301c
  - hspec-wai-json-0.11.0

docker:
  enable: false
  image: nejla/haskell-build

allow-newer: true

flags:
  nejla-common:
    # Required for lts < 19
    new-singletons: false

nix:
  shell-file: ../shell.nix
