resolver: lts-16.6

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 18ff4e9526d8f13e7abf84d30bd4977f4df96a51
  - '../auth-service-types'

docker:
  enable: false
  image: nejla/haskell-build

nix:
  packages:
    - zlib
    - postgresql
